hackmate/api/urls.py
import django.urls

import api.views


app_name = "api"

urlpatterns = [
    django.urls.path(
        "vacancies/",
        api.views.LoadMoreVacacncies.as_view(),
        name="vacancies",
    ),
    django.urls.path(
        "comments/<int:pk>/",
        api.views.LoadMoreComments.as_view(),
        name="comments",
    ),
]

hackmate/hackmate/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.urls
import notifications.urls


if django.conf.settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        django.urls.path(
            "__debug__/",
            django.urls.include(debug_toolbar.urls),
        ),
    ]

else:
    urlpatterns = []

urlpatterns += [
    django.urls.path("", django.urls.include("homepage.urls")),
    django.urls.path("auth/", django.urls.include("users.urls")),
    django.urls.path("vacancy/", django.urls.include("vacancies.urls")),
    django.urls.path("notification/", django.urls.include("notify.urls")),
    django.urls.path("api/", django.urls.include("api.urls")),
    django.urls.path("about/", django.urls.include("about.urls")),
    django.urls.path("admin/", django.contrib.admin.site.urls),
    django.urls.path("tinymce/", django.urls.include("tinymce.urls")),
    django.urls.path("i18n/", django.urls.include("django.conf.urls.i18n")),
    django.urls.re_path(
        "^inbox/notifications/",
        django.urls.include(notifications.urls, namespace="notifications"),
    ),
    django.urls.path(
        "ratings/",
        django.urls.include(
            ("star_ratings.urls"),
            namespace="ratings",
        ),
    ),
]

urlpatterns += django.conf.urls.static.static(
    django.conf.settings.MEDIA_URL,
    document_root=django.conf.settings.MEDIA_ROOT,
)

hackmate/users/urls.py
import django.contrib.auth.views
import django.urls

import users.forms
import users.views


app_name = "users"

login_view = django.contrib.auth.views.LoginView.as_view(
    template_name="users/login.html",
    form_class=users.forms.AuthenticateForm,
)
logout_view = django.contrib.auth.views.LogoutView.as_view(
    template_name="users/logout.html",
)
password_change_view = django.contrib.auth.views.PasswordChangeView.as_view(
    form_class=users.forms.PasswordChangeForm,
    template_name="users/password_change.html",
    success_url=django.urls.reverse_lazy("users:password_change_done"),
)
password_change_done_view = (
    django.contrib.auth.views.PasswordChangeDoneView.as_view(
        template_name="users/password_change_done.html",
    )
)
password_reset_view = django.contrib.auth.views.PasswordResetView.as_view(
    form_class=users.forms.PasswordResetForm,
    template_name="users/password_reset.html",
    email_template_name="users/password_reset_email.html",
    success_url=django.urls.reverse_lazy("users:password_reset_done"),
)
password_reset_done_view = (
    django.contrib.auth.views.PasswordResetDoneView.as_view(
        template_name="users/password_reset_done.html",
    )
)
password_reset_confirm_view = (
    django.contrib.auth.views.PasswordResetConfirmView.as_view(
        template_name="users/password_reset_confirm.html",
        form_class=users.forms.PasswordResetCompleteForm,
    )
)


urlpatterns = [
    django.urls.path(
        "signup/",
        users.views.SignUpView.as_view(),
        name="signup",
    ),
    django.urls.path(
        "profile/<str:username>/",
        users.views.ProfileView.as_view(),
        name="profile",
    ),
    django.urls.path(
        "profile_edit/",
        users.views.ProfileEditView.as_view(),
        name="profile_edit",
    ),
    django.urls.path(
        "profile_edit/delete_link/<int:pk>/",
        users.views.DeleteLinkView.as_view(),
        name="delete_link",
    ),
    django.urls.path(
        "login/",
        login_view,
        name="login",
    ),
    django.urls.path(
        "logout/",
        logout_view,
        name="logout",
    ),
    django.urls.path(
        "password_change/",
        password_change_view,
        name="password_change",
    ),
    django.urls.path(
        "password_change/done/",
        password_change_done_view,
        name="password_change_done",
    ),
    django.urls.path(
        "password_reset/",
        password_reset_view,
        name="password_reset",
    ),
    django.urls.path(
        "password_reset/done/",
        password_reset_done_view,
        name="password_reset_done",
    ),
    django.urls.path(
        "password_reset/confirm/<uidb64>/<token>/",
        password_reset_confirm_view,
        name="password_reset_confirm",
    ),
    django.urls.path(
        "activate/<str:username>/",
        users.views.ActivateUserView.as_view(),
        name="activate",
    ),
]

hackmate/vacancies/urls.py
import django.urls

import vacancies.views


app_name = "vacancies"

urlpatterns = [
    django.urls.path(
        "",
        vacancies.views.VacancyView.as_view(),
        name="vacancies",
    ),
    django.urls.path(
        "<int:pk>/",
        vacancies.views.VacancyDetailView.as_view(),
        name="vacancy_detail",
    ),
    django.urls.path(
        "my-vacancies/",
        vacancies.views.UserVacanciesView.as_view(),
        name="user_vacancies",
    ),
    django.urls.path(
        "create/",
        vacancies.views.VacancyCreateView.as_view(),
        name="vacancy_create",
    ),
    django.urls.path(
        "my-teams/",
        vacancies.views.UserTeamsView.as_view(),
        name="user_teams",
    ),
    django.urls.path(
        "delete_vacancy/<int:pk>/",
        vacancies.views.DeleteVacancy.as_view(),
        name="delete_vacancy",
    ),
    django.urls.path(
        "my-responses/",
        vacancies.views.UserResponsesView.as_view(),
        name="user_responses",
    ),
    django.urls.path(
        "delete_comment/<int:pk>/",
        vacancies.views.DeleteCommentView.as_view(),
        name="delete_comment",
    ),
    django.urls.path(
        "create_comment/<int:pk>/",
        vacancies.views.CreateCommentView.as_view(),
        name="create_comment",
    ),
    django.urls.path(
        "change_vacancy/<int:pk>/",
        vacancies.views.ChangeVacancyView.as_view(),
        name="change_vacancy",
    ),
    django.urls.path(
        "invite_user/<int:pk>/",
        vacancies.views.AcceptInvite.as_view(),
        name="invite_user",
    ),
    django.urls.path(
        "reject_user/<int:pk>/",
        vacancies.views.RejectInvite.as_view(),
        name="reject_user",
    ),
    django.urls.path(
        "kick_user/<int:pk>/<int:user_id>/",
        vacancies.views.KickUserFromVacancy.as_view(),
        name="kick_user",
    ),
]

hackmate/vacancies/views.py
__all__ = ()

import datetime
import re

import django.conf
import django.contrib
import django.contrib.auth.mixins
import django.contrib.messages
import django.db
import django.db.models
import django.http
import django.shortcuts
import django.urls
import django.utils.timezone
import django.utils.translation
import django.views
import django.views.generic

import vacancies.forms
import vacancies.models


user_model = django.contrib.auth.get_user_model()


def get_client_ip(request):
    x_forwarded_for = request.META.get("HTTP_X_FORWARDED_FOR")
    if x_forwarded_for:
        return x_forwarded_for.split(",")[0]

    return request.META.get("REMOTE_ADDR")


class VacancyView(django.views.generic.ListView):
    template_name = "vacancies/vacancies.html"
    model = vacancies.models.Vacancy
    context_object_name = "vacancies"

    def get_queryset(self):
        return vacancies.models.Vacancy.objects.select_related(
            "creater",
            "creater__profile",
        ).filter(
            status=vacancies.models.Vacancy.VacancyStatuses.ACTIVE,
            hackaton_date__gte=(
                django.utils.timezone.now() - datetime.timedelta(days=1)
            ),
        )[
            :10
        ]


class VacancyDetailView(
    django.views.generic.DetailView,
):
    model = vacancies.models.Vacancy
    template_name = "vacancies/detail.html"
    context_object_name = "vacancy"
    form_class = vacancies.forms.CommentForm

    def get_object(self):
        queryset = (
            self.get_queryset()
            .select_related("creater", "creater__profile")
            .prefetch_related(
                django.db.models.Prefetch(
                    "team_composition",
                    queryset=user_model.objects.select_related("profile"),
                ),
                "comments",
                django.db.models.Prefetch(
                    "comments__user",
                    queryset=user_model.objects.select_related("profile"),
                ),
            )
        )
        return django.shortcuts.get_object_or_404(
            queryset,
            pk=self.kwargs["pk"],
        )

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)

        ip = get_client_ip(request)
        ip_instance, created = vacancies.models.Ip.objects.get_or_create(ip=ip)
        if not self.object.views.filter(ip=ip_instance).exists():
            self.object.views.add(ip_instance)

        return response  # noqa ругается falke на то что пресваиваю response, хотя по его мнению можно было избежать этого было, но для оптимизации запросы мы должны брать объект из self.object, а если мы

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return django.http.JsonResponse(
                {
                    "error": django.utils.translation.gettext_lazy(
                        "Вы должны быть авторизованы",
                    ),
                },
                status=403,
            )

        vacancy = self.get_object()

        if vacancies.models.Response.objects.filter(
            vacancy=vacancy,
            user=request.user,
            status__in=[
                "not_answered",
                "accepted",
            ],
        ).exists():
            return django.http.JsonResponse(
                {
                    "message": django.utils.translation.gettext_lazy(
                        "Вы уже откликнулись на эту вакансию",
                    ),
                },
            )

        vacancies.models.Response.objects.create(
            vacancy=vacancy,
            user=request.user,
        )

        return django.http.JsonResponse(
            {
                "message": django.utils.translation.gettext_lazy(
                    "Ваш отклик отправлен!",
                ),
            },
        )

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comment_form"] = vacancies.forms.CommentForm()
        if self.request.user.is_authenticated:
            respnose_statuses = vacancies.models.Response.ResponseStatuses
            context["user_is_responsed"] = (
                self.get_object()
                .responses.filter(
                    user=self.request.user,
                    status__in=[
                        respnose_statuses.ACCEPTED,
                        respnose_statuses.NOT_ANSWERED,
                    ],
                )
                .exists()
            )
        else:
            context["user_is_responsed"] = False

        return context


class VacancyCreateView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.CreateView,
):
    model = vacancies.models.Vacancy
    form_class = vacancies.forms.VacancyForm
    template_name = "vacancies/vacancy_form.html"
    success_url = django.urls.reverse_lazy("vacancies:vacancies")

    def form_valid(self, form):
        form.instance.creater = self.request.user
        form.instance.status = vacancies.models.Vacancy.VacancyStatuses.ACTIVE
        return super().form_valid(form)


class UserResponsesView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.ListView,
):
    template_name = "vacancies/user_responses.html"
    context_object_name = "responses"

    def get_queryset(self):
        return vacancies.models.Response.objects.filter(
            user=self.request.user,
            status__in=[
                vacancies.models.Response.ResponseStatuses.NOT_ANSWERED,
                vacancies.models.Response.ResponseStatuses.ACCEPTED,
            ],
        ).annotate(
            active_vacancy=django.db.models.FilteredRelation(
                "vacancy",
                condition=django.db.models.Q(
                    vacancy__status__in=[
                        vacancies.models.Vacancy.VacancyStatuses.ACTIVE,
                        vacancies.models.Vacancy.VacancyStatuses.EQUIPPED,
                    ],
                    vacancy__hackaton_date__gte=(
                        django.utils.timezone.now()
                        - datetime.timedelta(days=1),
                    ),
                ),
            ),
        )


class UserVacanciesView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.ListView,
):
    model = vacancies.models.Vacancy
    template_name = "vacancies/user_vacancies.html"
    context_object_name = "vacancies"

    def get_queryset(self):
        return vacancies.models.Vacancy.objects.filter(
            creater=self.request.user,
            status__in=[
                vacancies.models.Vacancy.VacancyStatuses.ACTIVE,
                vacancies.models.Vacancy.VacancyStatuses.EQUIPPED,
            ],
        ).prefetch_related(
            django.db.models.Prefetch(
                "responses",
                queryset=vacancies.models.Response.objects.filter(
                    status=(
                        vacancies.models.Response.ResponseStatuses.NOT_ANSWERED
                    ),
                ),
            ),
        )


class CreateCommentView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.View,
):
    model = vacancies.models.CommentVacancy

    def get_success_url(self, requst, *args, **kwargs):
        return django.urls.reverse(
            "vacancies:vacancy_detail",
            args=[kwargs.get("pk")],
        )

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        vacancy = vacancies.models.Vacancy.objects.get(pk=kwargs.get("pk"))
        comment = request.POST.get("comment")
        if not re.search(django.conf.settings.BAD_WORDS_PATTERN, comment):
            vacancies.models.CommentVacancy.objects.create(
                vacancy=vacancy,
                user=request.user,
                comment=comment,
            )
        else:
            django.contrib.messages.error(
                request,
                django.utils.translation.gettext_lazy(
                    "В вашем комментарии присутствуют нецензурные слова"
                    ", поэтому он не будет отправлен",
                ),
            )

        return django.shortcuts.redirect(
            self.get_success_url(request, *args, **kwargs),
        )


class DeleteCommentView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.DeleteView,
):
    model = vacancies.models.CommentVacancy
    pk_url_kwarg = "pk"
    template_name = "vacancies/user_vacancies.html"

    def get_success_url(self, *args, **kwargs):
        return django.urls.reverse(
            "vacancies:vacancy_detail",
            args=[self.object.vacancy.pk],
        )

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()

        if self.object.user == request.user or request.user.is_superuser:
            return super(DeleteCommentView, self).delete(
                request,
                *args,
                **kwargs,
            )

        raise django.http.Http404(
            django.utils.translation.gettext_lazy("not found"),
        )


class DeleteVacancy(django.views.generic.DeleteView):
    model = vacancies.models.Vacancy
    pk_url_kwarg = "pk"

    def get_success_url(self, *args, **kwargs):
        return django.urls.reverse(
            "vacancies:vacancies",
        )

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()

        if self.object.creater == request.user or request.user.is_superuser:

hackmate/templates/vacancies/detail.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}

{% block links %}
	<link rel="stylesheet" href="{% static 'css/vacancies/detail.css' %}">
{% endblock %}

{% block content %}
	<div class="container vacancy-container">
		{% if messages %}
			<div class="messages" role="alert">
				{% for message in messages %}
					<p{% if message.tags %} class="alert alert-dark {{ message.tags }}"{% endif %}>{{ message }}</p>
				{% endfor %}
			</div>
		{% endif %}
		{% if vacancy.status == "active" %}
			{% if request.user == vacancy.creater %}
				<div class="dropdown">
					<button class="btn-vacancy-menu" type="button" data-bs-toggle="dropdown" aria-expanded="false"><i
							class="fa-solid fa-bars"></i></button>
					<ul class="dropdown-menu">
						<li><a class="dropdown-item"
						       href="{% url 'vacancies:change_vacancy' vacancy.pk %}">{% trans 'Изменить вакансию' %}</a></li>
						<hr>
						<li><a class="dropdown-item"
						       href="{% url 'vacancies:delete_vacancy' vacancy.pk %}">{% trans 'Удалить вакансию' %}</a></li>
					</ul>
				</div>
			{% endif %}
		{% endif %}
		<h1 class="vacancy-title">{{ vacancy.title }}</h1>
		<p class="vacancy-description">{{ vacancy.description|safe }}</p>

		<div class="vacancy-info">
			<p><strong>{% trans 'Создатель:' %}</strong> {{ vacancy.creater.username|truncatechars:200 }}</p>
			<p><strong>{% trans 'Создано:' %}</strong> {{ vacancy.created_at|date:"d.m.Y H:i" }}</p>
			{% if vacancy.hackaton_title %}
				<p><strong>{% trans 'Хакатон:' %}</strong> {{ vacancy.hackaton_title }}</p>
			{% endif %}
			{% if vacancy.hackaton_date %}
				<p><strong>{% trans 'Дата проведения хакатона' %}</strong>: {{ vacancy.hackaton_date|date:"d.m.Y" }}</p>
			{% endif %}
			{% if vacancy.required_experience %}
				<p><strong>{% trans 'Требуемый опыт:' %}</strong> {{ vacancy.get_required_experience_display }}</p>
			{% endif %}
			<p>
				<strong>{% trans 'Необходимое количество человек в группе для участия в хакатоне' %}:</strong> {{ vacancy.need_count_users }}
			</p>
			<article class="command">
				<p><strong>{% trans 'Текущий состав команды' %}:</strong></p>
				<article class="teammates">
					<a href="{% url 'users:profile' vacancy.creater.username %}" class="teammate">
						{% if vacancy.creater.profile.image %}
							<img src="{{ vacancy.creater.profile.image.url }}" class="teammate-image">
						{% else %}
							<img src="{% static 'img/default-avatar.jpg' %}" class="teammate-image">
						{% endif %}
						<p class="teammate-username teammate-admin-username">{{ vacancy.creater.username|truncatechars:50 }}</p>
					</a>
					{% for member in vacancy.team_composition.all %}
						<article class="teammate-article">
							<a href="{% url 'users:profile' member.username %}" class="teammate">
								{% if member.profile.image %}
									<img src="{{ member.profile.image.url }}" class="teammate-image">
								{% else %}
									<img src="{% static 'img/default-avatar.jpg' %}" class="teammate-image">
								{% endif %}
								<p class="teammate-username">{{ member.username|truncatechars:50 }}</p>
							</a>
							{% if request.user == vacancy.creater and vacancy.status == 'active' %}
								<a href="{% url 'vacancies:kick_user' vacancy.id member.pk %}"><i
										class="fa-solid fa-ban decline-user kick-teammate"></i></a>
							{% endif %}
						</article>
					{% endfor %}
				</article>
			</article>
		</div>

		<p class="views">
			<i class="fa-regular fa-eye"></i>{{ vacancy.views.count }}
		</p>

		{% if user.is_authenticated %}
			{% if user != vacancy.creater and not is_deadline_passed %}
				<button id="respond-button" class="grow-button {% if request.user in vacancy.team_composition.all or user_is_responsed %} grow-gray-button {% endif %}">{% trans 'Откликнуться' %}</button>
			{% endif %}
		{% else %}
			<p>{% trans 'Вы должны быть авторизованы, чтобы откликнуться.' %}</p>
		{% endif %}

		<section class="commnets" id="comments-container">
			<article class="create_comment">
				<h2 class="comments-header">{% trans 'Комментарии' %}</h2>
				<form method="post" action="{% url 'vacancies:create_comment' vacancy.pk %}">
					{% csrf_token %}
					<div class="form-group">
						{{ field.as_p }}
						{% for field in comment_form %}
							<div class="mb-3">
								{{ field }}
								{% if field.help_text %}
									<div class="form-text">{{ field.help_text }}</div>
								{% endif %}
								{% for error in field.errors %}
									<div class="text-danger">{{ error }}</div>
								{% endfor %}
							</div>
						{% endfor %}
					</div>
					<button type="submit" class="btn btn-primary send-comment">{% trans 'Отправить' %}</button>
				</form>
			</article>
			<input type="hidden" id="vacancy-id" value="{{ vacancy.id }}">
			<article class="comments">
				{% for comment in vacancy.comments.all|slice:":10" %}
					<div class="comment">
						<header class="comment-header">
							<a href="{% url 'users:profile' comment.user.username %}" class="user-a">
								{% if comment.user.profile.image %}
									<span class="comment-user"><img src="{{ comment.user.profile.image.url }}"
									                                class="user-image">{{ comment.user.username|truncatechars:50 }}</span>
								{% else %}
									<span class="comment-user"><img src="{% static 'img/default-avatar.jpg' %}"
									                                class="user-image">{{ comment.user.username|truncatechars:50 }}</span>
								{% endif %}
							</a>
							<figure>
								<span class="comment-date">{{ comment.created_at|date:"d.m.Y H:i" }}</span>
								{% if comment.user == request.user or request.user.is_superuser %}
									<a href="{% url 'vacancies:delete_comment' comment.pk %}" class="delete-link-form">❌</a>
								{% endif %}
							</figure>
						</header>
						<p class="comment-text">{{ comment.comment }}</p>
					</div>
					{% empty %}
					<p class="no-comments">{% trans 'Комментариев пока нет.' %}</p>
				{% endfor %}
			</article>
		</section>
	</div>
	<input type="hidden" id="vacancy-id" value="{{ vacancy.id }}">
	<script src="{% static 'js/load_more_comments.js' %}"></script>
	<script src="{% static 'js/button_detail.js' %}"></script>
{% endblock %}

hackmate/templates/vacancies/my_teams.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}

{% block links %}
	<link rel="stylesheet" href="{% static 'css/vacancies/my_vacancies.css' %}">
	<link rel="stylesheet" href="{% static 'css/vacancies/my_teams.css' %}">
{% endblock %}

{% block content %}
	<div class="container">
		<h1 class="page-title">{% trans 'Мои команды' %}</h1>
		{% if messages %}
			<div class="messages" role="alert">
				{% for message in messages %}
					<p{% if message.tags %} class="alert alert-dark {{ message.tags }}"{% endif %}>{{ message }}</p>
				{% endfor %}
			</div>
		{% endif %}
		<div class="vacancy-list">

			{% for vacancy in teams %}
				<div class="vacancy-item">
					<h4><a href="{% url 'vacancies:vacancy_detail' vacancy.pk %}" class="vacancy-title">
						{{ vacancy.title }}
					</a>
					</h4>
					<p class="vacancy-description">{{ vacancy.description|safe|truncatechars:200 }}</p>
					<p>{% trans 'Хакатон:' %} {{ vacancy.hackaton_title }}</p>
					<p>{% trans 'Дата проведения:' %} {{ vacancy.hackaton_date }}</p>
				<article class="command">
					<p><strong>{% trans 'Текущий состав команды' %}:</strong></p>
					<article class="teammates">
						<a href="{% url 'users:profile' vacancy.creater.username %}" class="teammate">
							{% if vacancy.creater.profile.image %}
								<img src="{{ vacancy.creater.profile.image.url }}" class="teammate-image">
							{% else %}
								<img src="{% static 'img/default-avatar.jpg' %}" class="teammate-image">
							{% endif %}
							<p class="teammate-username teammate-admin-username">{{ vacancy.creater.username|truncatechars:50 }}</p>
						</a>
						{% for member in vacancy.team_composition.all %}
							<article class="teammate-article">
								<a href="{% url 'users:profile' member.username %}" class="teammate">
									{% if member.profile.image %}
										<img src="{{ member.profile.image.url }}" class="teammate-image">
									{% else %}
										<img src="{% static 'img/default-avatar.jpg' %}" class="teammate-image">
									{% endif %}
									<p class="teammate-username">{{ member.username|truncatechars:50 }}</p>
								</a>
								{% if request.user == vacancy.creater and vacancy.status == 'active' %}
									<a href="{% url 'vacancies:kick_user' vacancy.id member.pk %}"><i
											class="fa-solid fa-ban decline-user kick-teammate"></i></a>
								{% endif %}
							</article>
						{% endfor %}
					</article>
				</article>
				</div>
				{% empty %}
				<article class="nothing-container">
					<h2 class="nothing">{% trans 'У вас нет вакансий' %}</h2>
					<p class="nothing">{% trans 'Если хотите создать анкету, то' %} <a href="{% url 'vacancies:vacancy_create' %}"
					                                                                   class="btn btn-link">{% trans 'перейдите сюда' %}</a>
					</p>
				</article>
			{% endfor %}
		</div>
	</div>
{% endblock %}

hackmate/templates/vacancies/user_responses.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}

{% block links %}
	<link rel="stylesheet" href="{% static 'css/vacancies/my_responses.css' %}">
{% endblock %}

{% block content %}
	<div class="container">
		<h1 class="page-title">{% trans 'Мои отклики' %}</h1>
		<div class="response-list">
			{% for response in responses %}
				<div class="response-item">
					<div>
						<a href="{% url 'vacancies:vacancy_detail' response.vacancy.pk %}" class="response-title">
							{{ response.vacancy.title }}
						</a>
						<p class="response-date">— {{ response.created_at|date:"d.m.Y H:i" }}</p>
					</div>
					<a href="{% url 'vacancies:vacancy_detail' response.vacancy.pk %}"
					   class="view-button">{% trans 'Посмотреть вакансию' %}</a>
				</div>
				{% empty %}
				<article class="nothing-container">
					<h2 class="nothing">{% trans 'У вас нету откликов.' %}</h2>
				</article>
			{% endfor %}
		</div>
	</div>
{% endblock %}


hackmate/templates/vacancies/user_vacancies.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}

{% block links %}
	<link rel="stylesheet" href="{% static 'css/vacancies/my_vacancies.css' %}">
{% endblock %}

{% block content %}
	<div class="container">
		<h1 class="page-title">{% trans 'Ваши вакансии' %}</h1>
		{% if messages %}
			<div class="messages" role="alert">
				{% for message in messages %}
					<p{% if message.tags %} class="alert alert-dark {{ message.tags }}"{% endif %}>{{ message }}</p>
				{% endfor %}
			</div>
		{% endif %}
		<div class="vacancy-list">
			{% for vacancy in vacancies %}
				<div class="vacancy-item">
					<a href="{% url 'vacancies:vacancy_detail' vacancy.pk %}" class="vacancy-title">
						{{ vacancy.title }}
					</a>
					<p class="vacancy-description">{{ vacancy.description|safe|truncatechars:200 }}</p>
					{% if vacancy.status == "active" %}
						<p class="vacancy-stats">{% trans 'Откликов' %}: {{ vacancy.responses.count }}</p>
						<div class="vacancy-responses">
							<h3>{% trans 'Откликнувшиеся пользователи:' %}</h3>
							<article class="responses-users">
								{% for response in vacancy.responses.all %}
									<article class="">
										<a href="{% url 'users:profile' response.user.username %}"
										   class="user-profile-link">{{ response.user.username }}</a>
									</article>
									<article>
										<a href="{% url 'vacancies:invite_user' response.id %}" class=""><i
												class="fa-solid fa-check accept-user"></i></a>
										<a href="{% url 'vacancies:reject_user' response.id %}" class=""><i
												class="fa-solid fa-ban decline-user"></i></a>
									</article>
									{% empty %}
									<a>{% trans 'Пока никто не откликнулся' %}</a>
								{% endfor %}
							</article>
						</div>
					{% endif %}
				</div>
				{% empty %}
				<article class="nothing-container">
					<h2 class="nothing">{% trans 'У вас нет вакансий' %}</h2>
					<p class="nothing">{% trans 'Если хотите создать анкету, то' %} <a href="{% url 'vacancies:vacancy_create' %}"
					                                                                   class="btn btn-link">{% trans 'перейдите сюда' %}</a>
					</p>
				</article>
			{% endfor %}
		</div>
	</div>
{% endblock %}