hackmate/about/urls.py
__all__ = ()

import about.views
import django.urls


app_name = "about"

urlpatterns = [
    django.urls.path(
        "",
        about.views.AboutPageView.as_view(),
        name="about",
    ),
    django.urls.path(
        "contact/",
        about.views.ContactPageView.as_view(),
        name="contact",
    ),
    django.urls.path(
        "privacy/",
        about.views.PrivacyPageView.as_view(),
        name="privacy",
    ),
]

hackmate/api/urls.py
import django.urls

import api.views


app_name = "api"

urlpatterns = [
    django.urls.path(
        "vacancies/",
        api.views.LoadMoreVacacncies.as_view(),
        name="vacancies",
    ),
    django.urls.path(
        "comments/<int:pk>/",
        api.views.LoadMoreComments.as_view(),
        name="comments",
    ),
]

hackmate/hackmate/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.urls
import notifications.urls


if django.conf.settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        django.urls.path(
            "__debug__/",
            django.urls.include(debug_toolbar.urls),
        ),
    ]

else:
    urlpatterns = []

urlpatterns += [
    django.urls.path("", django.urls.include("homepage.urls")),
    django.urls.path("auth/", django.urls.include("users.urls")),
    django.urls.path("vacancy/", django.urls.include("vacancies.urls")),
    django.urls.path("notification/", django.urls.include("notify.urls")),
    django.urls.path("api/", django.urls.include("api.urls")),
    django.urls.path("about/", django.urls.include("about.urls")),
    django.urls.path("admin/", django.contrib.admin.site.urls),
    django.urls.path("tinymce/", django.urls.include("tinymce.urls")),
    django.urls.path("i18n/", django.urls.include("django.conf.urls.i18n")),
    django.urls.re_path(
        "^inbox/notifications/",
        django.urls.include(notifications.urls, namespace="notifications"),
    ),
    django.urls.path(
        "ratings/",
        django.urls.include(
            ("star_ratings.urls"),
            namespace="ratings",
        ),
    ),
]

urlpatterns += django.conf.urls.static.static(
    django.conf.settings.MEDIA_URL,
    document_root=django.conf.settings.MEDIA_ROOT,
)

hackmate/homepage/urls.py
__all__ = ()

import django.urls

import homepage.views


app_name = "homepage"

urlpatterns = [
    django.urls.path(
        "",
        homepage.views.HomePageView.as_view(),
        name="homepage",
    ),
]

hackmate/notify/urls.py
import django.urls

import notify.views


app_name = "notify"

urlpatterns = [
    django.urls.path(
        "readall_notifications/",
        notify.views.ReadAllNotificationsView.as_view(),
        name="readall_notifications",
    ),
    django.urls.path(
        "readone_notification/<int:pk>",
        notify.views.ReadOneNotificationView.as_view(),
        name="readone_notification",
    ),
]

hackmate/users/urls.py
import django.contrib.auth.views
import django.urls

import users.forms
import users.views


app_name = "users"

login_view = django.contrib.auth.views.LoginView.as_view(
    template_name="users/login.html",
    form_class=users.forms.AuthenticateForm,
)
logout_view = django.contrib.auth.views.LogoutView.as_view(
    template_name="users/logout.html",
)
password_change_view = django.contrib.auth.views.PasswordChangeView.as_view(
    form_class=users.forms.PasswordChangeForm,
    template_name="users/password_change.html",
    success_url=django.urls.reverse_lazy("users:password_change_done"),
)
password_change_done_view = (
    django.contrib.auth.views.PasswordChangeDoneView.as_view(
        template_name="users/password_change_done.html",
    )
)
password_reset_view = django.contrib.auth.views.PasswordResetView.as_view(
    form_class=users.forms.PasswordResetForm,
    template_name="users/password_reset.html",
    email_template_name="users/password_reset_email.html",
    success_url=django.urls.reverse_lazy("users:password_reset_done"),
)
password_reset_done_view = (
    django.contrib.auth.views.PasswordResetDoneView.as_view(
        template_name="users/password_reset_done.html",
    )
)
password_reset_confirm_view = (
    django.contrib.auth.views.PasswordResetConfirmView.as_view(
        template_name="users/password_reset_confirm.html",
        form_class=users.forms.PasswordResetCompleteForm,
    )
)


urlpatterns = [
    django.urls.path(
        "signup/",
        users.views.SignUpView.as_view(),
        name="signup",
    ),
    django.urls.path(
        "profile/<str:username>/",
        users.views.ProfileView.as_view(),
        name="profile",
    ),
    django.urls.path(
        "profile_edit/",
        users.views.ProfileEditView.as_view(),
        name="profile_edit",
    ),
    django.urls.path(
        "profile_edit/delete_link/<int:pk>/",
        users.views.DeleteLinkView.as_view(),
        name="delete_link",
    ),
    django.urls.path(
        "login/",
        login_view,
        name="login",
    ),
    django.urls.path(
        "logout/",
        logout_view,
        name="logout",
    ),
    django.urls.path(
        "password_change/",
        password_change_view,
        name="password_change",
    ),
    django.urls.path(
        "password_change/done/",
        password_change_done_view,
        name="password_change_done",
    ),
    django.urls.path(
        "password_reset/",
        password_reset_view,
        name="password_reset",
    ),
    django.urls.path(
        "password_reset/done/",
        password_reset_done_view,
        name="password_reset_done",
    ),
    django.urls.path(
        "password_reset/confirm/<uidb64>/<token>/",
        password_reset_confirm_view,
        name="password_reset_confirm",
    ),
    django.urls.path(
        "activate/<str:username>/",
        users.views.ActivateUserView.as_view(),
        name="activate",
    ),
]

hackmate/templates/includes/footer.html
{% load tz %}
{% load static %}
{% load i18n %}

{% get_current_timezone as TIME_ZONE %}
{% timezone TIME_ZONE %}

	<footer class="footer">
		<div class="container">
			<div class="footer-content">
				<div class="footer-left">
					<h1 id="year">{% trans "HackMate" %} {% now "Y" %}</h1>
				</div>
				<div class="footer-center">
					<ul class="footer-links">
						<li><a href="{% url 'about:about' %}">{% trans "О проекте" %}</a></li>
						<li><a href="{% url 'about:contact' %}">{% trans "Контакты" %}</a></li>
						<li><a href="{% url 'about:privacy' %}">{% trans "Политика конфиденциальности" %}</a></li>
					</ul>
				</div>
				<div class="footer-right">
					<ul class="social-links">
						<li><a href="https://gitlab.crja72.ru/django/2024/autumn/course/projects/team-5" target="_blank">
							<i class="fa-brands fa-gitlab"></i>
							<p>{% trans "Проект на GitLab" %}</p>
						</a></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
{% endtimezone %}

hackmate/templates/includes/form.html
<div class="form-group">
	{{ field.label_tag }}
	{{ field }}
	{% for error in field.errors %}
		<div class="alert alert-danger">
			{{ error|escape }}
		</div>
	{% endfor %}
	<small id="emailHelp" class="form-text text-muted">{{ field.help_text }}</small>
</div>

hackmate/templates/includes/header.html
{% load i18n %}
{% load static %}
{% load notifications_tags %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<article class="navbar-nav list-group">
		{% with request.resolver_match.view_name as view_name %}
			{% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %}
			<a class="navbar-brand" href="{% url 'homepage:homepage' %}">
				<img src="{% static 'logo/favicon.ico' %}" width="48">
			</a>
			<a class="{% if view_name == 'homepage:homepage' %}list-group-item list-group-item-info {% endif %}"
			   href="{% url 'homepage:homepage' %}">{% trans "Главная" %}</a>
			<a class="{% if view_name == 'vacancies:vacancies' %}list-group-item list-group-item-info {% endif %}"
			   href="{% url 'vacancies:vacancies' %}">{% trans "Найти команду" %}</a>
			{% if not request.user.is_authenticated %}
				<a href="{% url 'users:signup' %}"
				   class="{% if view_name == 'users:signup' %}list-group-item list-group-item-info {% endif %}">{% trans "Регистрация" %}</a>
				<a href="{% url 'users:login' %}"
				   class="{% if view_name == 'users:login' %}list-group-item list-group-item-info {% endif %}">{% trans "Авторизация" %}</a>
			{% else %}
				<a href="{% url 'vacancies:user_responses' %}"
				   class="{% if view_name == 'vacancies:user_responses' %}list-group-item list-group-item-info {% endif %}">{% trans "Мои отклики" %}</a>
				<a href="{% url 'vacancies:user_vacancies' %}"
				   class="{% if view_name == 'vacancies:user_vacancies' %}list-group-item list-group-item-info {% endif %}">{% trans "Мои вакансии" %}</a>
				<a href="{% url 'vacancies:user_teams' %}"
				   class="{% if view_name == 'vacancies:user_teams' %}list-group-item list-group-item-info {% endif %}">{% trans "Мои команды" %}</a>
				<div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
					<ul class="navbar-nav">
						<li class="nav-item dropdown">
							<button class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
								{% if request.user.profile.image %}
									<img src="{{ request.user.profile.image.url }}" alt="" class="dropdown-image">
								{% else %}
									<img src="{% static 'img/default-avatar.jpg' %}" alt="Default Avatar" class="dropdown-image">
								{% endif %}
								<p class="dropdown-username">{{ request.user.username|truncatechars:40 }}</p>
							</button>
							<ul class="dropdown-menu">
								{% if request.user.is_superuser %}
									<li><a href="/admin/" class="dropdown-item">{% trans "Админка" %}</a></li>
								{% endif %}
								<li><a href="{% url 'users:profile' username=request.user %}"
								       class="dropdown-item">{% trans "Профиль" %}</a></li>
								<li><a href="{% url 'users:profile_edit' %}"
								       class="dropdown-item">{% trans "Редактирование профиля" %}</a></li>
								<li><a href="{% url 'users:password_change' %}" class="dropdown-item">{% trans "Изменить пароль" %}</a>
								</li>
								<li><a href="{% url 'users:logout' %}" class="dropdown-item">{% trans "Выйти" %}</a></li>
							</ul>
						</li>
					</ul>
				</div>
				<div class="dropdown">
					{% with request.user.notifications.unread as unread_notifications %}
						<a href="#" id="notificationDropdown" data-bs-toggle="dropdown" aria-expanded="false" class="bell-link">
							<i class="fa fa-bell"></i>
							{% if unread_notifications %}
								<span class="badge bg-danger">{{ unread_notifications|length }}</span>
							{% endif %}
						</a>
						<ul class="dropdown-menu dropdown-menu-end" aria-labelledby="notificationDropdown">
							{% if unread_notifications %}
								{% for notification in unread_notifications %}
									<li class="notification-dropdown-item-li">
										<p class="dropdown-item dropdown-item-notify" href="#">
											<a href="{% url 'users:profile' notification.actor %}" class="notification-profile-link">
												{{ notification.actor|truncatechars:30 }}</a> {{ notification.verb }} -
											{{ notification.timestamp|date:"d.m.Y H:i" }}
										</p>
										<a href="{% url 'notify:readone_notification' notification.pk %}" class="readone_notification">⨯</a>
									</li>
								{% endfor %}
								<li>
									<hr class="dropdown-divider">
								</li>
								<li class="notification-dropdown-item-li">
									<a class="dropdown-item dropdown-item-notify"
									   href="{% url 'notify:readall_notifications' %}">{% trans "Отметить все как прочитанные" %}</a>
								</li>
							{% else %}
								<li>
									<p class="dropdown-item text-muted dropdown-item-notify"
									   href="#">{% trans "Нет новых уведомлений" %}</p>
								</li>
							{% endif %}
						</ul>
					{% endwith %}
				</div>
			{% endif %}
		{% endwith %}
	</article>
	<article>
		<form action="{% url 'set_language' %}" method="post" class="d-flex set-language-form">
			{% csrf_token %}
			<input name="next" type="hidden" value="{{ request.get_full_path }}">
			<select name="language" class="form-select">
				{% get_current_language as LANGUAGE_CODE %}
				<option value="ru" {% if LANGUAGE_CODE == 'ru' %}selected{% endif %}>Русский</option>
				<option value="en" {% if LANGUAGE_CODE == 'en' %}selected{% endif %}>English</option>
			</select>
			<button type="submit" class="btn border-white ms-2 btn-dark">{% trans "Сменить" %}</button>
		</form>
	</article>
</nav>

hackmate/templates/includes/infinite_scroll.html
{% load static %}

<script src="{% static 'js/load_more.js' %}"></script>