hackmate/api/urls.py
import django.urls

import api.views


app_name = "api"

urlpatterns = [
    django.urls.path(
        "vacancies/",
        api.views.LoadMoreVacacncies.as_view(),
        name="vacancies",
    ),
    django.urls.path(
        "comments/<int:pk>/",
        api.views.LoadMoreComments.as_view(),
        name="comments",
    ),
]

hackmate/hackmate/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.urls
import notifications.urls


if django.conf.settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        django.urls.path(
            "__debug__/",
            django.urls.include(debug_toolbar.urls),
        ),
    ]

else:
    urlpatterns = []

urlpatterns += [
    django.urls.path("", django.urls.include("homepage.urls")),
    django.urls.path("auth/", django.urls.include("users.urls")),
    django.urls.path("vacancy/", django.urls.include("vacancies.urls")),
    django.urls.path("notification/", django.urls.include("notify.urls")),
    django.urls.path("api/", django.urls.include("api.urls")),
    django.urls.path("about/", django.urls.include("about.urls")),
    django.urls.path("admin/", django.contrib.admin.site.urls),
    django.urls.path("tinymce/", django.urls.include("tinymce.urls")),
    django.urls.path("i18n/", django.urls.include("django.conf.urls.i18n")),
    django.urls.re_path(
        "^inbox/notifications/",
        django.urls.include(notifications.urls, namespace="notifications"),
    ),
    django.urls.path(
        "ratings/",
        django.urls.include(
            ("star_ratings.urls"),
            namespace="ratings",
        ),
    ),
]

urlpatterns += django.conf.urls.static.static(
    django.conf.settings.MEDIA_URL,
    document_root=django.conf.settings.MEDIA_ROOT,
)

hackmate/users/urls.py
import django.contrib.auth.views
import django.urls

import users.forms
import users.views


app_name = "users"

login_view = django.contrib.auth.views.LoginView.as_view(
    template_name="users/login.html",
    form_class=users.forms.AuthenticateForm,
)
logout_view = django.contrib.auth.views.LogoutView.as_view(
    template_name="users/logout.html",
)
password_change_view = django.contrib.auth.views.PasswordChangeView.as_view(
    form_class=users.forms.PasswordChangeForm,
    template_name="users/password_change.html",
    success_url=django.urls.reverse_lazy("users:password_change_done"),
)
password_change_done_view = (
    django.contrib.auth.views.PasswordChangeDoneView.as_view(
        template_name="users/password_change_done.html",
    )
)
password_reset_view = django.contrib.auth.views.PasswordResetView.as_view(
    form_class=users.forms.PasswordResetForm,
    template_name="users/password_reset.html",
    email_template_name="users/password_reset_email.html",
    success_url=django.urls.reverse_lazy("users:password_reset_done"),
)
password_reset_done_view = (
    django.contrib.auth.views.PasswordResetDoneView.as_view(
        template_name="users/password_reset_done.html",
    )
)
password_reset_confirm_view = (
    django.contrib.auth.views.PasswordResetConfirmView.as_view(
        template_name="users/password_reset_confirm.html",
        form_class=users.forms.PasswordResetCompleteForm,
    )
)


urlpatterns = [
    django.urls.path(
        "signup/",
        users.views.SignUpView.as_view(),
        name="signup",
    ),
    django.urls.path(
        "profile/<str:username>/",
        users.views.ProfileView.as_view(),
        name="profile",
    ),
    django.urls.path(
        "profile_edit/",
        users.views.ProfileEditView.as_view(),
        name="profile_edit",
    ),
    django.urls.path(
        "profile_edit/delete_link/<int:pk>/",
        users.views.DeleteLinkView.as_view(),
        name="delete_link",
    ),
    django.urls.path(
        "login/",
        login_view,
        name="login",
    ),
    django.urls.path(
        "logout/",
        logout_view,
        name="logout",
    ),
    django.urls.path(
        "password_change/",
        password_change_view,
        name="password_change",
    ),
    django.urls.path(
        "password_change/done/",
        password_change_done_view,
        name="password_change_done",
    ),
    django.urls.path(
        "password_reset/",
        password_reset_view,
        name="password_reset",
    ),
    django.urls.path(
        "password_reset/done/",
        password_reset_done_view,
        name="password_reset_done",
    ),
    django.urls.path(
        "password_reset/confirm/<uidb64>/<token>/",
        password_reset_confirm_view,
        name="password_reset_confirm",
    ),
    django.urls.path(
        "activate/<str:username>/",
        users.views.ActivateUserView.as_view(),
        name="activate",
    ),
]

hackmate/vacancies/urls.py
import django.urls

import vacancies.views


app_name = "vacancies"

urlpatterns = [
    django.urls.path(
        "",
        vacancies.views.VacancyView.as_view(),
        name="vacancies",
    ),
    django.urls.path(
        "<int:pk>/",
        vacancies.views.VacancyDetailView.as_view(),
        name="vacancy_detail",
    ),
    django.urls.path(
        "my-vacancies/",
        vacancies.views.UserVacanciesView.as_view(),
        name="user_vacancies",
    ),
    django.urls.path(
        "create/",
        vacancies.views.VacancyCreateView.as_view(),
        name="vacancy_create",
    ),
    django.urls.path(
        "my-teams/",
        vacancies.views.UserTeamsView.as_view(),
        name="user_teams",
    ),
    django.urls.path(
        "delete_vacancy/<int:pk>/",
        vacancies.views.DeleteVacancy.as_view(),
        name="delete_vacancy",
    ),
    django.urls.path(
        "my-responses/",
        vacancies.views.UserResponsesView.as_view(),
        name="user_responses",
    ),
    django.urls.path(
        "delete_comment/<int:pk>/",
        vacancies.views.DeleteCommentView.as_view(),
        name="delete_comment",
    ),
    django.urls.path(
        "create_comment/<int:pk>/",
        vacancies.views.CreateCommentView.as_view(),
        name="create_comment",
    ),
    django.urls.path(
        "change_vacancy/<int:pk>/",
        vacancies.views.ChangeVacancyView.as_view(),
        name="change_vacancy",
    ),
    django.urls.path(
        "invite_user/<int:pk>/",
        vacancies.views.AcceptInvite.as_view(),
        name="invite_user",
    ),
    django.urls.path(
        "reject_user/<int:pk>/",
        vacancies.views.RejectInvite.as_view(),
        name="reject_user",
    ),
    django.urls.path(
        "kick_user/<int:pk>/<int:user_id>/",
        vacancies.views.KickUserFromVacancy.as_view(),
        name="kick_user",
    ),
]

hackmate/users/views.py
__all__ = []

import django.conf
import django.contrib.auth
import django.contrib.auth.decorators
import django.contrib.auth.mixins
import django.contrib.auth.models
import django.contrib.auth.views
import django.contrib.messages
import django.core.exceptions
import django.core.mail
import django.forms
import django.http
import django.shortcuts
import django.urls
import django.utils.timezone
import django.utils.translation
import django.views
import django.views.generic
import star_ratings.models

import users.forms
import users.models
import vacancies.models

User = django.contrib.auth.get_user_model()


class DeleteLinkView(django.views.generic.DeleteView):
    model = users.models.ProfileLink
    pk_url_kwarg = "pk"
    success_url = django.urls.reverse_lazy("users:profile_edit")

    def get_queryset(self):
        return super().get_queryset().select_related("profile__user")

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.profile.user != request.user:
            django.contrib.messages.error(
                request,
                django.utils.translation.gettext_lazy(
                    "Вы не можете удалить эту ссылку.",
                ),
            )
            return django.shortcuts.redirect(self.success_url)

        self.object.delete()
        return django.shortcuts.redirect(self.success_url)


class ProfileView(django.views.generic.View):
    def get(self, request, username):
        user = django.shortcuts.get_object_or_404(
            users.models.User.objects.select_related("profile"),
            username=username,
        )
        finished_vacancies = (
            vacancies.models.Vacancy.objects.filter(
                creater_id=user.id,
                status=vacancies.models.Vacancy.VacancyStatuses.EQUIPPED,
            )
            .select_related("creater")
            .prefetch_related("responses")
        )

        is_own_profile = user == request.user
        rating_user = star_ratings.models.Rating.objects.filter(
            object_id=user.id,
        ).first()

        return django.shortcuts.render(
            request,
            "users/profile.html",
            {
                "user": user,
                "is_own_profile": is_own_profile,
                "rating_user": rating_user,
                "finished_vacancies": finished_vacancies,
            },
        )


class ProfileEditView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.View,
):

    def get(self, request):
        user = users.models.User.objects.select_related("profile").get(
            pk=request.user.pk,
        )
        image_form = users.forms.ProfileImageChangeForm(instance=user.profile)
        form = users.forms.UserChangeForm(instance=user)
        profile_form = users.forms.ProfileChangeForm(instance=user.profile)
        link_form = users.forms.ProfileLinkForm()
        links = users.models.ProfileLink.objects.filter(
            profile=request.user.profile,
        ).select_related("profile")

        return django.shortcuts.render(
            request,
            "users/profile_edit.html",
            {
                "image_form": image_form,
                "form": form,
                "profile_form": profile_form,
                "link_form": link_form,
                "links": links,
            },
        )

    def post(self, request):
        user = users.models.User.objects.select_related("profile").get(
            pk=request.user.pk,
        )
        image_form = users.forms.ProfileImageChangeForm(
            request.POST,
            request.FILES,
            instance=user.profile,
        )
        form = users.forms.UserChangeForm(request.POST, instance=user)
        profile_form = users.forms.ProfileChangeForm(
            request.POST,
            instance=user.profile,
        )
        link_form = users.forms.ProfileLinkForm(request.POST)

        if not form.data.get("email") or not form.data.get("username"):
            django.contrib.messages.error(
                request,
                django.utils.translation.gettext_lazy(
                    "Поля Email и Username обязательны для заполнения.",
                ),
            )
            return django.shortcuts.render(
                request,
                "users/profile_edit.html",
                {"form": form, "profile_form": profile_form},
            )

        if form.is_valid() and profile_form.is_valid():
            user_form = form.save(commit=False)
            user_form.mail = users.models.UserManager().normalize_email(
                form.cleaned_data["email"],
            )

            if link_form.is_valid() and link_form.cleaned_data.get("url"):
                link = link_form.save(commit=False)
                link.profile = request.user.profile
                link.save()

            user_form.save()
            profile_form.save()
            image_form.save()
            django.contrib.messages.success(
                request,
                django.utils.translation.gettext_lazy(
                    "Профиль успешно изменен!",
                ),
            )
            return django.shortcuts.redirect("users:profile_edit")

        return django.shortcuts.render(
            request,
            "users/profile_edit.html",
            {
                "image_form": image_form,
                "form": form,
                "profile_form": profile_form,
                "link_form": link_form,
            },
        )


class SignUpView(django.views.generic.FormView):
    template_name = "users/signup.html"
    form_class = users.forms.UserCreateForm
    success_url = django.urls.reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.email = users.models.UserManager().normalize_email(
            form.cleaned_data["email"],
        )
        user.set_password(form.cleaned_data["password1"])

        if django.conf.settings.DEFAULT_USER_IS_ACTIVE:
            user.is_active = True
        else:
            user.is_active = False
            url = django.urls.reverse("users:activate", args=[user.username])
            domain = self.request.get_host()
            confirmation_link = (
                django.utils.translation.gettext_lazy(
                    "Чтобы подтвердить аккаунт перейдите по ссылке ",
                )
                + f"http://{domain}{url}"
            )

            django.core.mail.send_mail(
                django.utils.translation.gettext_lazy("Activate your account"),
                confirmation_link,
                django.conf.settings.EMAIL_HOST_USER,
                [user.email],
                fail_silently=False,
            )

        user.save()

        django.contrib.messages.success(
            self.request,
            django.utils.translation.gettext_lazy(
                "Пользователь успешно создан",
            ),
        )
        django.contrib.messages.info(
            self.request,
            django.utils.translation.gettext_lazy(
                "Активируйте профиль в письме, которое придет вам на почту",
            ),
        )

        return super().form_valid(form)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))


class ActivateUserView(django.views.View):
    def get(self, request, username):
        user = django.shortcuts.get_object_or_404(User, username=username)

        if user.is_active:
            django.contrib.messages.error(
                request,
                django.utils.translation.gettext_lazy(
                    "Пользователь уже активирован",
                ),
            )
            return django.shortcuts.redirect("users:login")

        if self.can_activate_user(user):
            user.is_active = True
            user.save()
            django.contrib.messages.success(
                request,
                django.utils.translation.gettext_lazy(
                    "Пользователь успешно активирован",
                ),
            )
        else:
            django.contrib.messages.error(
                request,
                django.utils.translation.gettext_lazy(
                    "Активация профиля была доступна в течение "
                    f"{self.get_allowed_activation_time(user)} "
                    "часов после регистрации",
                ),
            )

        return django.shortcuts.redirect(django.urls.reverse("users:login"))

    def can_activate_user(self, user):
        now = django.utils.timezone.now()
        time_difference = now - (
            user.profile.date_last_active or user.date_joined
        )
        allowed_hours = self.get_allowed_activation_time(user)
        return time_difference.total_seconds() // 3600 <= allowed_hours

    def get_allowed_activation_time(self, user):
        return 168 if user.profile.date_last_active else 12


class CustomPasswordResetCompleteView(
    django.contrib.auth.views.PasswordResetCompleteView,
):
    template_name = "users/password_reset_confirm.html"
    form_class = users.forms.PasswordResetCompleteForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = self.form_class()
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            return django.http.HttpResponseRedirect(
                django.urls.reverse_lazy("users:password_reset_complete"),
            )

        return django.shortcuts.render(
            request,
            self.template_name,
            {"form": form},
        )

hackmate/templates/users/login.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}

{% block links %}
	<link rel="stylesheet" href="{% static 'css/users/signup.css' %}">
{% endblock %}

{% block content %}
	<section class="container">
		{% if messages %}
			<div class="messages" role="alert">
				{% for message in messages %}
					<p{% if message.tags %} class="alert alert-dark {{ message.tags }}"{% endif %}>{{ message }}</p>
				{% endfor %}
			</div>
		{% endif %}

		<article class="form">
			<form method="post" enctype="multipart/form-data" class="form-group">
				{% csrf_token %}
				{% for field in form %}
					{% include "includes/form.html" %}
				{% endfor %}
				<button type="submit" class="grow-button">{% trans "Отправить" %}</button>
			</form>
		</article>
		<a href="{% url 'users:password_reset' %}" class="password">{% trans "Восстановить пароль" %}</a>
	</section>
{% endblock %}

hackmate/templates/users/logout.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
	<section class="container">
		<div class="alert alert-dark" role="alert" style="margin-top: 50px;">
			{% trans "Вы вышли из аккаунта" %}
		</div>
	</section>
{% endblock %}

hackmate/templates/users/password_change.html
{% extends "base.html" %}

{% load static %}

{% block links %}
	<link rel="stylesheet" href="{% static 'css/users/password_reset.css' %}">
{% endblock %}

{% load i18n %}

{% block content %}
	<section class="container">
		<form method="POST" action="" class="change-password-form">
			{% csrf_token %}
			{% for field in form %}
				{% include "includes/form.html" %}
			{% endfor %}
			<button type="submit" class="grow-button">{% trans "Сменить" %}</button>
		</form>
	</section>
{% endblock %}

hackmate/templates/users/password_change_done.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
	<section class="container">
		<div class="alert alert-success" role="alert" style="margin-top: 50px;">
			{% trans "Пароль успешно поменяли" %}
		</div>
	</section>
{% endblock %}

hackmate/templates/users/password_reset.html
{% extends "base.html" %}
{% load static %}

{% load i18n %}

{% block links %}
	<link rel="stylesheet" href="{% static 'css/users/password_reset.css' %}">
{% endblock %}

{% block content %}
	<section class="container">
		<form method="POST" class="password-reset">
			{% csrf_token %}
			{% for field in form %}
				{% include "includes/form.html" %}
			{% endfor %}
			<button type="submit" class="grow-button">{% trans 'Восстановить' %}</button>
		</form>
	</section>
{% endblock %}

hackmate/templates/users/password_reset_complete.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
	<form method="POST" action="">
		{% csrf_token %}
		{% for field in form %}
			{% include "includes/form.html" %}
		{% endfor %}
		<button type="submit" class="btn btn-primary" grow-button>{% trans "Выйти" %}</button>
	</form>
{% endblock %}

hackmate/templates/users/password_reset_confirm.html
{% extends "base.html" %}

{% load static %}

{% block links %}
	<link rel="stylesheet" href="{% static 'css/users/password_reset.css' %}">
{% endblock %}

{% block content %}
	<section class="container">
		<form method="POST" class="password-reset">
			{% csrf_token %}
			{% for field in form %}
				{% include "includes/form.html" %}
			{% endfor %}
			<button type="submit" class="grow-button">{% trans "Выйти" %}</button>
		</form>
	</section>
{% endblock %}

hackmate/templates/users/password_reset_done.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
	<section class="container">
		<div class="alert alert-success" role="alert" style="margin-top: 50px;">
			{% trans "Проверьте почту для успешного восттановления пароля" %}
		</div>
	</section>
{% endblock %}

hackmate/templates/users/password_reset_email.html
{% autoescape off %}
Нажмите на ссылку внизу:

{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

Если переход по ссылке выше не работает, пожалуйста, скопируйте и вставьте URL-адрес в новое
окно браузера.

{% endautoescape %}

hackmate/templates/users/profile.html
{% extends "base.html" %}

{% load static %}
{% load ratings %}
{% load i18n %}

{% block links %}
	<link rel="stylesheet" href="{% static 'css/users/profile.css' %}">
{% endblock %}

{% block content %}
	<section class="container profile-section">
		<div class="profile-header">
			<div class="profile-rating">
				<div class="stars">
					{% if is_own_profile %}
						<article>
							<h4>{% trans 'Рейтинг' %}: {{ rating_user.average|floatformat:1|default:"0" }}</h4>
							<h4>{% trans 'Количество оценок' %}: {{ rating_user.count|default:"0" }}</h4>
						</article>
					{% else %}
						{% ratings user.profile %}
					{% endif %}
				</div>

			</div>
		</div>
		<div class="profile-avatar">
			{% if user.profile.image %}
				<img src="{{ user.profile.image.url }}" alt="{{ user.username }}" class="avatar">
			{% else %}
				<img src="{% static 'img/default-avatar.jpg' %}" alt="{% trans 'Default Avatar' %}" class="avatar">
			{% endif %}
		</div>
		<div class="profile-info">

			<h1>{{ user.username }}</h1>
			<p class="email"><strong>{% trans "Email" %}:</strong><a href="mailto:{{ user.email }}">{{ user.email }}</a></p>

			<div class="profile-details">
				<div class="profile-item">
					{% if user.profile.description %}
						<p><strong>{% trans 'О себе' %} </strong> {{ user.profile.description }}</p>
					{% else %}
						<p><strong>{% trans 'О себе' %}:</strong>{% trans 'Информация не указана' %}.</p>
					{% endif %}
				</div>

				<div class="profile-item">
					{% if user.profile.birthday %}
						<p><strong>{% trans 'День рождения' %}:</strong> {{ user.profile.birthday }}</p>
					{% else %}
						<p><strong>{% trans 'День рождения' %}:</strong> {% trans 'Информация не указана.' %}</p>
					{% endif %}
				</div>

				<div class="profile-item">
					<p><strong>{% trans 'Дата регистрации' %}:</strong> {{ user.date_joined|date:"d.m.Y" }}</p>
				</div>
			</div>
		</div>

		<div class="links-section">
			<h2>{% trans 'Ссылки на другие сети' %}</h2>

			{% if user.profile.links.exists %}
				<ul class="social-links">
					{% for link in user.profile.links.all %}
						<li>
							<h5>
								<a href="{{ link.url }}" target="_blank" title="{{ link.get_site_type_display }}" class="btn btn-link">
									<i class="fab {{ link.get_fa_icon_class }} site-icon"></i>
									{{ link.site_type }}
								</a>
							</h5>
						</li>
					{% endfor %}
				</ul>
			{% else %}
				<p>{% trans 'Ссылки отсутствуют.' %}</p>
			{% endif %}
		</div>

		{% if is_own_profile %}
			<div class="profile-actions">
				<a href="{% url 'users:profile_edit' %}"
				   class="grow-button">{% trans 'Редактировать профиль' %}</a>
			</div>
		{% endif %}

		<h2 class="finished-vacancies-title">{% trans 'Завершённые вакансии' %}</h2>
		{% for vacancy in finished_vacancies %}
			<div class="card w-75 mb-3">
				<div class="card-body">
					<h5 class="card-title">{{ vacancy.title }}</h5>
					<p class="card-text">{{ vacancy.description|truncatechars:200|safe }}</p>
					<a href="{% url 'vacancies:vacancy_detail' vacancy.pk %}" class="grow-button">{% trans 'Детальнее' %}</a>
				</div>
			</div>
			{% empty %}
			<p class="no-vacancies">{% trans 'У пользователя' %} {{ user.username }} {% trans 'нет завершённых вакансий' %}.</p>
		{% endfor %}
	</section>

	<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
	<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
{% endblock %}

hackmate/templates/users/profile_edit.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}

{% block links %}
	<link rel="stylesheet" href="{% static 'css/users/profile_edit.css' %}">
{% endblock %}

{% block content %}
	<section class="container">
		<h1>{% trans "Редактирование профиля" %}</h1>

		{% if messages %}
			<div class="messages" role="alert">
				{% for message in messages %}
					<p{% if message.tags %} class="alert alert-dark {{ message.tags }}"{% endif %}>{{ message }}</p>
				{% endfor %}
			</div>
		{% endif %}

		<form method="post" enctype="multipart/form-data" class="edit-profile-form">
			{% csrf_token %}

			<div class="form-group">
				<label for="id_image">{% trans "Аватар" %}</label><br>

				{% if user.profile.image %}
					<img src="{{ user.profile.image.url }}" alt="{% trans 'Текущий аватар' %}"
					     class="img-thumbnail mb-3 current-avatar">
					<form method="post">
						{% csrf_token %}
						<button type="submit" name="delete_image" value="true" class="btn btn-danger delete-profile-image">
							{% trans "Удалить изображение" %}
						</button>
					</form>

				{% else %}
					<p class="text-muted">{% trans "Аватар отсутствует" %}</p>
				{% endif %}
				{% for field in image_form %}
					{% include "includes/form.html" %}
				{% endfor %}

				{% for field in form %}
					{% include "includes/form.html" %}
				{% endfor %}
				{% for field in profile_form %}
					{% include "includes/form.html" %}
				{% endfor %}

				<h2 class="add-new-link-title">{% trans "Добавить новую ссылку" %}</h2>
				{% for field in link_form %}
					{% include "includes/form.html" %}
				{% endfor %}
				<button type="submit" name="add_link"
				        class="grow-button btn-confirm-changes">{% trans "Сохранить изменения" %}</button>
		</form>

		{% if user.profile.links.exists %}
			<h2 class="other-social-links-title">{% trans "Ссылки на другие сети" %}</h2>
			<ul>
				{% for link in user.profile.links.all %}
					<li class="li-links">
						<a href="{{ link.url }}" target="_blank" title="{{ link.get_site_type_display }}">
							<i class="fab {{ link.get_fa_icon_class }} site-icon"></i>
							{{ link.site_type }}
						</a>
						<form method="post" action="{% url 'users:delete_link' pk=link.pk %}" class="delete-link-form">
							{% csrf_token %}
							<button type="submit" class="close delete-link-button" aria-label="Close">
								<span aria-hidden="true">&times;</span>
							</button>
						</form>
					</li>
				{% endfor %}
			</ul>
		{% endif %}
		<div class="password-container">
			<a href="{% url 'users:password_change' %}" class="password">{% trans "Изменить пароль" %}</a>
		</div>
	</section>
{% endblock %}

hackmate/templates/users/signup.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}

{% block links %}
	<link rel="stylesheet" href="{% static 'css/users/signup.css' %}">
{% endblock %}

{% block content %}
	<section class="container">
		{% if messages %}
			<div class="messages" role="alert">
				{% for message in messages %}
					<p{% if message.tags %} class="alert alert-dark {{ message.tags }}"{% endif %}>{{ message }}</p>
				{% endfor %}
			</div>
		{% endif %}
		<form method="post" enctype="multipart/form-data" class="form">
			{% csrf_token %}
			{% for field in form %}
				{% include "includes/form.html" %}
			{% endfor %}
			<button type="submit" class="grow-button">{% trans 'Отправить' %}</button>
		</form>
	</section>
{% endblock %}